### ISSUE TITLE
curlをrequestライブラリで置き換えたい

### ISSUE THREAD

**Issue by sakkuntyo** [sakkuntyo/discord-pero#3]
requestでやってみているけどうまくいかない

現状
```bash
curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json https://texttospeech.googleapis.com/v1/text:synthesize
```

これを↓みたいなかんじで置き換えたい
translateConfigはこのままでよさそう

```js
var translateConfig = {
  audioConfig: {
    audioEncoding: "LINEAR16",
    pitch: 0,
    speakingRate: 1
  },
  input: {
    text: secondory_msg
  },
  voice: {
    languageCode: "en-US",
    name: "en-US-Wavenet-D"
  }
}
var options = {
  url: 'https://texttospeech.googleapis.com/v1/text:synthesize',
  method: "POST",
  form: JSON.stringify(translateConfig),
  headers: {
    'Authorization': "Bearer " + execSync("gcloud auth application-default print-access-token"),
    'Content-Type': "application/json; charset=utf-8"
  },
  json: true
}
request(options, (err,res,body) => {
  console.log(err);
  console.log(res);
  console.log(body);
});
```

Authorizationがどうたらこうたらってエラーが出る

**Comment by sakkuntyo** [comment]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at Object.request (https.js:289:10)
    at Request.start (/root/discord-pero/node_modules/request/request.js:751:32)
    at Request.write (/root/discord-pero/node_modules/request/request.js:1497:10)
    at end (/root/discord-pero/node_modules/request/request.js:549:18)
    at Immediate._onImmediate (/root/discord-pero/node_modules/request/request.js:578:7)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
